import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import jsYaml from "js-yaml";
import type {
  NormalizedContext,
  NormalizedCommandSet,
  NormalizedCommand,
  NormalizedExit,
  Option,
  Argument,
  JsonSchema,
  Components,
} from "../types.js";

export interface TypeScriptGeneratorOptions {
  emitTypes?: boolean;
  emitClient?: boolean;
  emitValidators?: boolean;
  emitProgram?: boolean;
  contractYaml?: string;
}

export interface TypeScriptOutput {
  [filename: string]: string;
}

export function generateTypeScript(
  ctx: NormalizedContext,
  options: TypeScriptGeneratorOptions = {},
): TypeScriptOutput {
  const {
    emitTypes = true,
    emitClient = true,
    emitValidators = true,
    emitProgram = true,
    contractYaml,
  } = options;

  const hasEffects = contextHasEffects(ctx);
  const hasExtract = contractYaml !== undefined;

  const output: TypeScriptOutput = {
    "index.ts": generateIndex(ctx, { emitProgram, hasEffects, hasExtract }),
    "types.ts": emitTypes ? generateTypes(ctx) : "// types generation disabled\nexport {};\n",
    "commands.ts": emitClient ? generateCommands(ctx) : "// client generation disabled\nexport {};\n",
    "schemas.ts": emitValidators ? generateSchemas(ctx) : "// validators generation disabled\nexport {};\n",
  };

  if (emitProgram) {
    output["program.ts"] = generateProgram(ctx, contractYaml);
  }

  if (hasExtract && contractYaml) {
    output["contract.ts"] = generateContractModule(ctx, contractYaml);
  }

  if (hasEffects) {
    output["policy.ts"] = generatePolicyModule(ctx);
    output["policy-runtime.ts"] = loadPolicyRuntime();
  }

  return output;
}

function generateIndex(
  ctx: NormalizedContext,
  opts: { emitProgram: boolean; hasEffects: boolean; hasExtract: boolean },
): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by cli-contracts. Do not edit.");
  lines.push('export * from "./types.js";');
  lines.push('export * from "./commands.js";');
  lines.push('export * from "./schemas.js";');
  if (opts.emitProgram) {
    lines.push('export { createProgram } from "./program.js";');
    lines.push('export type { CommandHandlers } from "./program.js";');
  }
  if (opts.hasEffects) {
    lines.push('export { commandDefinitions, deriveCommandPolicy } from "./policy.js";');
  }
  if (opts.hasExtract) {
    lines.push('export { CONTRACT_YAML, CONTRACT_JSON_STR } from "./contract.js";');
  }
  lines.push("");
  return lines.join("\n");
}

function generateTypes(ctx: NormalizedContext): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by cli-contracts. Do not edit.");
  lines.push("");

  for (const cs of ctx.command_sets) {
    for (const cmd of cs.commands) {
      generateCommandTypes(cmd, cs, lines, ctx.components);
    }
  }

  if (ctx.components.schemas) {
    for (const [name, schema] of Object.entries(ctx.components.schemas)) {
      generateSchemaType(name, schema, lines);
    }
  }

  return lines.join("\n");
}

function generateCommandTypes(
  cmd: NormalizedCommand,
  cs: NormalizedCommandSet,
  lines: string[],
  components: Components,
): void {
  const prefix = toPascalCase(cmd.id);

  // Arguments type
  if (cmd.arguments.length > 0) {
    lines.push(`export interface ${prefix}Args {`);
    for (const arg of cmd.arguments) {
      const optional = arg.required ? "" : "?";
      const tsType = arg.variadic ? "string[]" : jsonSchemaToTs(arg.schema);
      lines.push(`  ${toCamelCase(arg.name)}${optional}: ${tsType};`);
    }
    lines.push("}");
    lines.push("");
  }

  // Options type
  if (cmd.options.length > 0) {
    lines.push(`export interface ${prefix}Options {`);
    for (const opt of cmd.options) {
      const optional = opt.required ? "" : "?";
      const tsType = jsonSchemaToTs(opt.schema);
      lines.push(`  ${toCamelCase(opt.name)}${optional}: ${tsType};`);
    }
    lines.push("}");
    lines.push("");
  }

  if (cmd.exits.length > 0) {
    const exitCodes = cmd.exits.map((e) => e.exit_code);
    lines.push(`export type ${prefix}ExitCode = ${exitCodes.join(" | ")};`);
    lines.push("");

    const resultVariants: string[] = [];
    for (const exit of cmd.exits) {
      const variant = buildExitResultVariant(exit, prefix, components);
      resultVariants.push(variant);
    }
    lines.push(`export type ${prefix}ExitResult =`);
    lines.push(`  ${resultVariants.join("\n  | ")};`);
    lines.push("");
  }
}

function buildExitResultVariant(
  exit: NormalizedExit,
  prefix: string,
  components: Components,
): string {
  const parts: string[] = [`exitCode: ${exit.exit_code}`];

  if (exit.stdout) {
    const type = resolveOutputType(exit.stdout.schema, components);
    const opt = exit.stdout.required === false ? "?" : "";
    parts.push(`stdout${opt}: ${type}`);
  }

  if (exit.stderr) {
    const type = resolveOutputType(exit.stderr.schema, components);
    const opt = exit.stderr.required === false ? "?" : "";
    parts.push(`stderr${opt}: ${type}`);
  }

  return `{ ${parts.join("; ")} }`;
}

function resolveOutputType(
  schema: JsonSchema | undefined,
  components: Components,
): string {
  if (!schema) return "unknown";
  if (schema.$ref) {
    const name = refToTypeName(schema.$ref);
    return name;
  }
  return jsonSchemaToTs(schema);
}

function generateCommands(ctx: NormalizedContext): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by cli-contracts. Do not edit.");
  lines.push('import { execFile } from "node:child_process";');
  lines.push('import { promisify } from "node:util";');
  lines.push("");
  lines.push("const execFileAsync = promisify(execFile);");
  lines.push("");

  lines.push("export interface ExecResult {");
  lines.push("  exitCode: number;");
  lines.push("  stdout: string;");
  lines.push("  stderr: string;");
  lines.push("}");
  lines.push("");

  for (const cs of ctx.command_sets) {
    for (const cmd of cs.commands) {
      generateCommandFunction(cmd, cs, lines);
    }
  }

  return lines.join("\n");
}

function generateCommandFunction(
  cmd: NormalizedCommand,
  cs: NormalizedCommandSet,
  lines: string[],
): void {
  const funcName = toCamelCase(cmd.full_id);
  const prefix = toPascalCase(cmd.id);
  const hasArgs = cmd.arguments.length > 0;
  const hasOpts = cmd.options.length > 0;

  const params: string[] = ["executable: string"];
  if (hasArgs) params.push(`args: import("./types.js").${prefix}Args`);
  if (hasOpts) params.push(`options?: Partial<import("./types.js").${prefix}Options>`);

  lines.push(`export async function ${funcName}(`);
  lines.push(`  ${params.join(",\n  ")},`);
  lines.push(`): Promise<ExecResult> {`);
  lines.push(`  const cmdArgs: string[] = ${JSON.stringify(cmd.path)};`);

  if (hasArgs) {
    for (const arg of cmd.arguments) {
      const name = toCamelCase(arg.name);
      if (arg.variadic) {
        lines.push(`  if (args.${name}) cmdArgs.push(...args.${name});`);
      } else {
        lines.push(`  if (args.${name} !== undefined) cmdArgs.push(String(args.${name}));`);
      }
    }
  }

  if (hasOpts) {
    lines.push("  if (options) {");
    for (const opt of cmd.options) {
      const name = toCamelCase(opt.name);
      const flag = `--${opt.name}`;
      if (opt.schema?.type === "boolean") {
        lines.push(`    if (options.${name}) cmdArgs.push("${flag}");`);
      } else {
        lines.push(`    if (options.${name} !== undefined) cmdArgs.push("${flag}", String(options.${name}));`);
      }
    }
    lines.push("  }");
  }

  lines.push("");
  lines.push("  try {");
  lines.push("    const result = await execFileAsync(executable, cmdArgs);");
  lines.push("    return { exitCode: 0, stdout: result.stdout, stderr: result.stderr };");
  lines.push("  } catch (err: unknown) {");
  lines.push("    const e = err as { code?: number; stdout?: string; stderr?: string };");
  lines.push("    return {");
  lines.push("      exitCode: typeof e.code === 'number' ? e.code : 1,");
  lines.push("      stdout: e.stdout ?? '',");
  lines.push("      stderr: e.stderr ?? '',");
  lines.push("    };");
  lines.push("  }");
  lines.push("}");
  lines.push("");
}

function generateSchemas(ctx: NormalizedContext): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by cli-contracts. Do not edit.");
  lines.push("");

  if (!ctx.components.schemas || Object.keys(ctx.components.schemas).length === 0) {
    lines.push("export {};");
    lines.push("");
    return lines.join("\n");
  }

  lines.push("export const schemas = {");
  for (const [name, schema] of Object.entries(ctx.components.schemas)) {
    lines.push(`  ${name}: ${JSON.stringify(schema, null, 2).replace(/\n/g, "\n  ")},`);
  }
  lines.push("} as const;");
  lines.push("");

  for (const cs of ctx.command_sets) {
    for (const cmd of cs.commands) {
      const prefix = toPascalCase(cmd.id);
      const exitCodes = cmd.exits.map((e) => e.exit_code);
      lines.push(`export const ${toCamelCase(cmd.id)}ExitCodes = [${exitCodes.join(", ")}] as const;`);
    }
  }
  lines.push("");

  return lines.join("\n");
}

function generateSchemaType(
  name: string,
  schema: JsonSchema,
  lines: string[],
): void {
  if (schema.allOf) {
    generateAllOfSchemaType(name, schema.allOf, lines);
  } else if (schema.type === "object" && schema.properties) {
    lines.push(`export interface ${name} {`);
    const required = new Set(schema.required ?? []);
    for (const [prop, propSchema] of Object.entries(schema.properties)) {
      const opt = required.has(prop) ? "" : "?";
      const tsType = jsonSchemaToTs(propSchema);
      lines.push(`  ${prop}${opt}: ${tsType};`);
    }
    lines.push("}");
    lines.push("");
  } else if (schema.type === "array" && schema.items) {
    lines.push(`export type ${name} = ${jsonSchemaToTs(schema.items)}[];`);
    lines.push("");
  } else if (schema.enum) {
    const values = schema.enum.map((v) =>
      typeof v === "string" ? `"${v}"` : String(v),
    );
    lines.push(`export type ${name} = ${values.join(" | ")};`);
    lines.push("");
  } else {
    lines.push(`export type ${name} = ${jsonSchemaToTs(schema)};`);
    lines.push("");
  }
}

function generateAllOfSchemaType(
  name: string,
  allOf: JsonSchema[],
  lines: string[],
): void {
  const bases: string[] = [];
  const ownProps = new Map<string, { optional: boolean; tsTypes: string[] }>();

  for (const sub of allOf) {
    if (sub.$ref) {
      bases.push(refToTypeName(sub.$ref));
    } else if (sub.type === "object" && sub.properties) {
      const required = new Set(sub.required ?? []);
      for (const [key, propSchema] of Object.entries(sub.properties)) {
        const tsType = jsonSchemaToTs(propSchema);
        const merged = ownProps.get(key);
        if (!merged) {
          ownProps.set(key, { optional: !required.has(key), tsTypes: [tsType] });
          continue;
        }
        // Every allOf branch has to hold at once, so a property required by
        // any branch is required and differing types intersect.
        merged.optional = merged.optional && !required.has(key);
        if (!merged.tsTypes.includes(tsType)) merged.tsTypes.push(tsType);
      }
    } else {
      bases.push(jsonSchemaToTs(sub));
    }
  }

  if (ownProps.size > 0) {
    const extendsClause = bases.length > 0 ? ` extends ${bases.join(", ")}` : "";
    lines.push(`export interface ${name}${extendsClause} {`);
    for (const [key, prop] of ownProps) {
      const opt = prop.optional ? "?" : "";
      const tsType =
        prop.tsTypes.length === 1
          ? prop.tsTypes[0]
          : prop.tsTypes.map((t) => `(${t})`).join(" & ");
      lines.push(`  ${key}${opt}: ${tsType};`);
    }
    lines.push("}");
    lines.push("");
  } else if (bases.length > 0) {
    lines.push(`export type ${name} = ${bases.join(" & ")};`);
    lines.push("");
  } else {
    lines.push(`export type ${name} = unknown;`);
    lines.push("");
  }
}

function jsonSchemaToTs(schema?: JsonSchema): string {
  if (!schema) return "unknown";
  if (schema.$ref) return refToTypeName(schema.$ref);

  if (schema.oneOf) {
    return schema.oneOf.map(jsonSchemaToTs).join(" | ");
  }
  if (schema.anyOf) {
    return schema.anyOf.map(jsonSchemaToTs).join(" | ");
  }
  if (schema.allOf) {
    return schema.allOf.map(jsonSchemaToTs).join(" & ");
  }

  if (schema.enum) {
    return schema.enum
      .map((v) => (typeof v === "string" ? `"${v}"` : String(v)))
      .join(" | ");
  }

  switch (schema.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return `${jsonSchemaToTs(schema.items)}[]`;
    case "object":
      if (schema.properties) {
        const required = new Set(schema.required ?? []);
        const props = Object.entries(schema.properties)
          .map(([k, v]) => {
            const opt = required.has(k) ? "" : "?";
            return `${k}${opt}: ${jsonSchemaToTs(v)}`;
          })
          .join("; ");
        return `{ ${props} }`;
      }
      if (
        schema.additionalProperties === true ||
        typeof schema.additionalProperties === "object"
      ) {
        return "Record<string, unknown>";
      }
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

function refToTypeName(ref: string): string {
  const parts = ref.split("/");
  return parts[parts.length - 1];
}

function toPascalCase(str: string): string {
  return str
    .split(/[.\-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function toCamelCase(str: string): string {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

const JS_RESERVED = new Set([
  "break", "case", "catch", "class", "const", "continue", "debugger",
  "default", "delete", "do", "else", "export", "extends", "false",
  "finally", "for", "function", "if", "import", "in", "instanceof",
  "let", "new", "null", "return", "super", "switch", "this", "throw",
  "true", "try", "typeof", "undefined", "var", "void", "while", "with",
  "yield", "enum", "await", "implements", "interface", "package",
  "private", "protected", "public", "static",
]);

function safeIdentifier(name: string): string {
  const camel = toCamelCase(name);
  return JS_RESERVED.has(camel) ? `${camel}Arg` : camel;
}

// ─── program.ts generator ───────────────────────────────────────

function generateProgram(ctx: NormalizedContext, contractYaml?: string): string {
  const lines: string[] = [];
  const hasEffects = contextHasEffects(ctx);
  const allCommandIds = ctx.command_sets.flatMap((cs) =>
    cs.commands.map((c) => c.id),
  );
  const hasUserExtract = allCommandIds.includes("extract");
  const injectExtract = contractYaml !== undefined && !hasUserExtract;

  lines.push("// Auto-generated by cli-contracts. Do not edit.");
  lines.push('import { Command } from "commander";');
  if (hasEffects) {
    // The program body only derives policy. commandDefinitions stays internal to
    // policy.ts and reaches consumers through the index.ts re-export.
    lines.push('import { deriveCommandPolicy } from "./policy.js";');
  }
  if (injectExtract) {
    lines.push('import { CONTRACT_YAML, CONTRACT_JSON_STR } from "./contract.js";');
  }
  lines.push("");

  // Build the CommandHandlers interface
  lines.push("export interface CommandHandlers {");
  for (const cs of ctx.command_sets) {
    for (const cmd of cs.commands) {
      const handlerName = toCamelCase(cmd.id);
      const sig = buildHandlerSignature(cmd);
      lines.push(`  ${handlerName}: ${sig};`);
    }
  }
  lines.push("}");
  lines.push("");

  // Build createProgram function
  lines.push("export function createProgram(");
  lines.push("  handlers: CommandHandlers,");
  lines.push("  version: string,");
  lines.push("): Command {");
  lines.push("  const program = new Command();");

  // Assumes single command set for program name; use first
  const primaryCs = ctx.command_sets[0];
  lines.push(`  program`);
  lines.push(`    .name(${JSON.stringify(primaryCs.executable)})`);
  lines.push(`    .version(version, "-V, --version")`);
  lines.push(
    `    .description(${JSON.stringify(primaryCs.summary ?? ctx.info.description ?? "")});`,
  );
  lines.push("");

  for (const opt of primaryCs.global_options) {
    const skipBuiltins = ["version", "help"];
    if (skipBuiltins.includes(opt.name)) continue;
    const optFlag = buildOptionFlag(opt);
    const desc = JSON.stringify(opt.description ?? "");
    const def = opt.schema?.default;
    if (def !== undefined) {
      const defValue = commanderDefaultValue(def, opt.schema?.type);
      lines.push(
        `  program.option(${JSON.stringify(optFlag)}, ${desc}, ${defValue});`,
      );
    } else {
      lines.push(
        `  program.option(${JSON.stringify(optFlag)}, ${desc});`,
      );
    }
  }

  if (hasEffects) {
    lines.push(
      `  program.option("--introspect", "Output derived policy as JSON without executing the command");`,
    );
  }
  lines.push("");

  // Commands (nested paths register parent subcommands once)
  const cmdRegistrationState: CommandRegistrationState = {
    createdPrefixes: new Set(),
    groups: {},
  };
  for (const cs of ctx.command_sets) {
    cmdRegistrationState.groups = cs.groups;
    for (const cmd of cs.commands) {
      generateProgramCommand(cmd, lines, hasEffects, cmdRegistrationState);
    }
  }

  if (injectExtract) {
    generateBuiltinExtractCommand(ctx, lines);
  }

  lines.push("  return program;");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function buildHandlerSignature(cmd: NormalizedCommand): string {
  const params: string[] = [];

  for (const arg of cmd.arguments) {
    const type = arg.variadic ? "string[]" : "string | undefined";
    params.push(`${safeIdentifier(arg.name)}: ${type}`);
  }

  const optFields = cmd.options.map((o) => {
    const type = o.schema?.type === "boolean" ? "boolean" : "string";
    return `${toCamelCase(o.name)}?: ${type}`;
  });
  if (commandIsLlmPowered(cmd) && !commandHasManualShowPrompt(cmd)) {
    optFields.push("showPrompt?: boolean");
  }

  if (optFields.length > 0) {
    params.push(`options: { ${optFields.join("; ")} }`);
  } else {
    params.push("options: Record<string, never>");
  }

  params.push("parentOpts: Record<string, unknown>");

  const isLlm = commandIsLlmPowered(cmd);
  const returnType = isLlm ? "Promise<void | string>" : "Promise<void>";
  return `(${params.join(", ")}) => ${returnType}`;
}

interface CommandRegistrationState {
  createdPrefixes: Set<string>;
  /** Parent command-group metadata for the active command set, keyed by dotted-path prefix. */
  groups: Record<string, import("../schema.js").Group>;
}

function commandParentVarName(prefixSegments: string[]): string {
  return `__cmd_${prefixSegments.join("_")}`;
}

function prefixKey(segments: string[]): string {
  return segments.join("\0");
}

/** Ensures ancestor subcommands exist; returns the receiver for the leaf command. */
function ensureCommandAncestors(
  path: string[],
  state: CommandRegistrationState,
  lines: string[],
): string {
  if (path.length <= 1) {
    return "program";
  }

  for (let depth = 1; depth < path.length; depth++) {
    const prefix = path.slice(0, depth);
    const key = prefixKey(prefix);
    if (state.createdPrefixes.has(key)) continue;

    const segment = path[depth - 1]!;
    const parentVar =
      depth === 1 ? "program" : commandParentVarName(path.slice(0, depth - 1));
    const varName = commandParentVarName(prefix);

    // A groups entry keyed by this prefix's dotted path supplies a group-level
    // description. When absent, output is byte-identical to prior behavior.
    const group = state.groups[prefix.join(".")];
    const groupDesc = group?.description ?? group?.summary;

    if (groupDesc !== undefined) {
      lines.push(
        `  const ${varName} = ${parentVar}.command(${JSON.stringify(segment)}).description(${JSON.stringify(groupDesc)});`,
      );
    } else {
      lines.push(
        `  const ${varName} = ${parentVar}.command(${JSON.stringify(segment)});`,
      );
    }
    state.createdPrefixes.add(key);
  }

  return commandParentVarName(path.slice(0, -1));
}

function generateProgramCommand(
  cmd: NormalizedCommand,
  lines: string[],
  hasEffects: boolean = false,
  registrationState?: CommandRegistrationState,
): void {
  const handlerName = toCamelCase(cmd.id);
  const path = cmd.path;
  const state = registrationState ?? { createdPrefixes: new Set(), groups: {} };
  const receiver =
    path.length === 1 ? "program" : ensureCommandAncestors(path, state, lines);
  // An empty path means the command is invoked without a subcommand name.
  // commander still needs a name to register it under, so the command id
  // supplies one and the registration carries isDefault so it runs when no
  // subcommand is given, and hidden so help keeps advertising the bare form.
  const isDefaultCommand = path.length === 0;
  const nameSegments = isDefaultCommand ? cmd.id.split(".") : path;
  const commandName = nameSegments[nameSegments.length - 1];
  if (commandName === undefined || commandName === "") {
    throw new Error(`Command ${cmd.id} has no name to register`);
  }
  const commandArgs = isDefaultCommand
    ? `${JSON.stringify(commandName)}, { isDefault: true, hidden: true }`
    : JSON.stringify(commandName);

  lines.push(`  ${receiver}`);
  lines.push(`    .command(${commandArgs})`);
  lines.push(`    .description(${JSON.stringify(cmd.summary)})`);

  // Arguments
  for (const arg of cmd.arguments) {
    const token = arg.variadic
      ? arg.required ? `<${arg.name}...>` : `[${arg.name}...]`
      : arg.required ? `<${arg.name}>` : `[${arg.name}]`;
    const desc = JSON.stringify(arg.description ?? "");
    lines.push(`    .argument(${JSON.stringify(token)}, ${desc})`);
  }

  for (const opt of cmd.options) {
    const flag = buildOptionFlag(opt);
    const desc = JSON.stringify(opt.description ?? "");
    const def = opt.schema?.default;
    if (def !== undefined) {
      const defValue = commanderDefaultValue(def, opt.schema?.type);
      lines.push(
        `    .option(${JSON.stringify(flag)}, ${desc}, ${defValue})`,
      );
    } else {
      lines.push(`    .option(${JSON.stringify(flag)}, ${desc})`);
    }
  }

  if (commandIsLlmPowered(cmd) && !commandHasManualShowPrompt(cmd)) {
    lines.push(
      `    .option("--show-prompt", "Output the constructed prompt without calling the LLM API.", false)`,
    );
  }

  const argSafeNames = cmd.arguments.map((a) => safeIdentifier(a.name));
  const isLlm = commandIsLlmPowered(cmd);
  const hasOpts = cmd.options.length > 0 || isLlm;
  // commander passes (...args, opts, cmd) positionally, so opts stays declared
  // even when the body reads nothing from it. Underscore keeps that declaration
  // out of the way of the consumer's noUnusedParameters.
  const optsParam = hasOpts || hasEffects ? "opts" : "_opts";
  const actionParams = [...argSafeNames, optsParam, "cmd"];

  lines.push(
    `    .action(async (${actionParams.join(", ")}) => {`,
  );

  if (hasEffects) {
    lines.push("      const globalOpts = cmd.optsWithGlobals();");
    lines.push("      if (globalOpts.introspect) {");
    lines.push(`        const policy = deriveCommandPolicy(${JSON.stringify(cmd.id)}, opts);`);
    lines.push("        console.log(JSON.stringify(policy, null, 2));");
    lines.push("        return;");
    lines.push("      }");
  }

  const callArgs = [
    ...argSafeNames,
    hasOpts ? "opts" : "{}",
    hasEffects ? "globalOpts" : "cmd.optsWithGlobals()",
  ];

  if (isLlm) {
    lines.push("      if (opts.showPrompt) {");
    lines.push(
      `        const prompt = await handlers.${handlerName}(${callArgs.join(", ")});`,
    );
    lines.push("        if (typeof prompt === \"string\") process.stdout.write(prompt + \"\\n\");");
    lines.push("        return;");
    lines.push("      }");
  }

  lines.push(
    `      await handlers.${handlerName}(${callArgs.join(", ")});`,
  );
  lines.push("    });");
  lines.push("");
}

function commanderDefaultValue(
  def: unknown,
  schemaType?: string | string[],
): string {
  if (typeof def === "boolean") return JSON.stringify(def);
  if (typeof def === "string") return JSON.stringify(def);
  // Commander expects string defaults for non-boolean options
  return JSON.stringify(String(def));
}

function contextHasEffects(ctx: NormalizedContext): boolean {
  for (const cs of ctx.command_sets) {
    for (const cmd of cs.commands) {
      if (cmd.effects) return true;
      for (const opt of cmd.options) {
        if (opt.effects) return true;
      }
    }
  }
  return false;
}

function commandIsLlmPowered(cmd: NormalizedCommand): boolean {
  return cmd.options.some((o) => o.name === "adapter");
}

function commandHasManualShowPrompt(cmd: NormalizedCommand): boolean {
  return cmd.options.some((o) => o.name === "show-prompt");
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

function loadPolicyRuntime(): string {
  const pkgRoot = resolve(__dirname, "..", "..");
  const runtimePath = resolve(pkgRoot, "src", "policy-runtime.ts");
  return readFileSync(runtimePath, "utf-8");
}

function generatePolicyModule(ctx: NormalizedContext): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by cli-contracts. Do not edit.");
  lines.push('import { derivePolicy, isOptionActive } from "./policy-runtime.js";');
  lines.push('import type { DerivedPolicy, IntrospectionResult } from "./policy-runtime.js";');
  lines.push("");
  lines.push("export type { DerivedPolicy, IntrospectionResult };");
  lines.push("");

  lines.push("export const commandDefinitions = {");
  for (const cs of ctx.command_sets) {
    for (const cmd of cs.commands) {
      const raw = cmd as unknown as Record<string, unknown>;
      const cmdDef: Record<string, unknown> = {};

      if (cmd.effects) {
        cmdDef.effects = cmd.effects;
      }

      const optionDefs: Record<string, unknown>[] = [];
      for (const opt of cmd.options) {
        const optDef: Record<string, unknown> = {
          name: opt.name,
        };
        if (opt.schema) optDef.schema = opt.schema;
        if (opt.file) optDef.file = opt.file;
        if (opt.effects) optDef.effects = opt.effects;
        if (opt.repeatable) optDef.repeatable = opt.repeatable;
        optionDefs.push(optDef);
      }
      if (optionDefs.length > 0) {
        cmdDef.options = optionDefs;
      }

      const envDef: Record<string, unknown> = {};
      if (cs.env) {
        for (const [envName, envVar] of Object.entries(cs.env)) {
          if (envVar.sensitive) {
            envDef[envName] = { sensitive: true };
          }
        }
      }
      if (Object.keys(envDef).length > 0) {
        cmdDef.env = envDef;
      }

      lines.push(`  ${JSON.stringify(cmd.id)}: ${JSON.stringify(cmdDef, null, 2).replace(/\n/g, "\n  ")},`);
    }
  }
  lines.push("} as const;");
  lines.push("");

  lines.push(
    "export function deriveCommandPolicy(",
  );
  lines.push("  command_id: string,");
  lines.push("  optionValues: Record<string, unknown>,");
  lines.push("): IntrospectionResult {");
  lines.push("  const def = commandDefinitions[command_id as keyof typeof commandDefinitions];");
  lines.push('  if (!def) throw new Error(`Unknown command: ${command_id}`);');
  lines.push("");
  lines.push("  // eslint-disable-next-line @typescript-eslint/no-explicit-any");
  lines.push("  const cmdDef = def as any;");
  lines.push("  const options: Record<string, { value: unknown; specified: boolean; definition: any }> = {};");
  lines.push("  const active_options: string[] = [];");
  lines.push("");
  lines.push("  for (const optDef of cmdDef.options ?? []) {");
  lines.push("    const value = optionValues[optDef.name];");
  lines.push("    const specified = optDef.name in optionValues && value !== undefined;");
  lines.push("    options[optDef.name] = { value, specified, definition: optDef };");
  lines.push("    if (isOptionActive(optDef, value, specified)) {");
  lines.push("      active_options.push(optDef.name);");
  lines.push("    }");
  lines.push("  }");
  lines.push("");
  lines.push("  const policy = derivePolicy({");
  lines.push("    command_id,");
  lines.push("    command_effects: cmdDef.effects,");
  lines.push("    options,");
  lines.push("    env: cmdDef.env,");
  lines.push("  });");
  lines.push("");
  lines.push("  return { command: command_id, active_options, policy };");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function buildOptionFlag(opt: Option): string {
  const parts: string[] = [];
  if (opt.aliases && opt.aliases.length > 0) {
    parts.push(`-${opt.aliases[0]}`);
  }
  const isBoolean = opt.schema?.type === "boolean";
  if (isBoolean) {
    parts.push(`--${opt.name}`);
  } else {
    const valueName = opt.value_name ?? "value";
    if (opt.repeatable) {
      parts.push(`--${opt.name} <${valueName}...>`);
    } else {
      parts.push(`--${opt.name} <${valueName}>`);
    }
  }
  return parts.join(", ");
}

// ─── contract.ts generator ──────────────────────────────────────

function generateContractModule(
  ctx: NormalizedContext,
  contractYaml: string,
): string {
  const jsonDoc = buildContractJson(ctx, contractYaml);
  const jsonStr = JSON.stringify(jsonDoc, null, 2);

  const lines: string[] = [];
  lines.push("// Auto-generated by cli-contracts. Do not edit.");
  lines.push("// Embedded contract for the extract subcommand.");
  lines.push("");
  lines.push(`export const CONTRACT_YAML: string = ${JSON.stringify(contractYaml)};`);
  lines.push("");
  lines.push(`export const CONTRACT_JSON_STR: string = ${JSON.stringify(jsonStr)};`);
  lines.push("");
  return lines.join("\n");
}

function buildContractJson(
  _ctx: NormalizedContext,
  contractYaml: string,
): Record<string, unknown> {
  return jsYaml.load(contractYaml) as Record<string, unknown>;
}

// ─── built-in extract command injection ─────────────────────────

function generateBuiltinExtractCommand(
  ctx: NormalizedContext,
  lines: string[],
): void {
  const executable = ctx.command_sets[0].executable;
  const allFullIds = ctx.command_sets.flatMap((cs) =>
    cs.commands.map((c) => c.full_id),
  );

  lines.push("");
  lines.push("  // Built-in extract command (auto-injected by cli-contracts)");
  lines.push("  program");
  lines.push('    .command("extract")');
  lines.push('    .description("Extract contract specification for this CLI tool.")');
  lines.push('    .argument("[commands...]", "Command IDs to extract. Use dot notation.")');
  lines.push('    .option("-a, --all", "Extract all commands.", false)');
  lines.push('    .option("--include-meta", "Include extraction metadata.", true)');
  lines.push('    .option("-F, --format <format>", "Output format (yaml or json).", "yaml")');
  lines.push("    .action(async (commands: string[], opts: { all?: boolean; includeMeta?: boolean; format?: string }) => {");
  lines.push("      if (commands.length === 0 && !opts.all) {");
  lines.push('        process.stderr.write(JSON.stringify({ code: "INVALID_ARGS", message: "Specify command IDs or use --all" }) + "\\n");');
  lines.push("        process.exit(2);");
  lines.push("      }");
  lines.push("");
  lines.push("      const format = opts.format || \"yaml\";");
  lines.push("      const doc = JSON.parse(CONTRACT_JSON_STR);");
  lines.push("      const cmdIds = opts.all ? [] : commands;");
  lines.push("");
  lines.push("      if (cmdIds.length === 0) {");
  lines.push("        // --all: output full contract");
  lines.push("        if (format === \"json\") {");
  lines.push("          const out: Record<string, unknown> = {};");
  lines.push("          if (opts.includeMeta) {");
  lines.push(`            out._meta = {`);
  lines.push(`              source: "embedded",`);
  lines.push(`              type: "cli-contracts/extract",`);
  lines.push(`              extractedAt: new Date().toISOString(),`);
  lines.push(`              specVersion: doc.cli_contracts ?? "0.1.0",`);
  lines.push(`              commands: ${JSON.stringify(allFullIds)},`);
  lines.push(`            };`);
  lines.push("          }");
  lines.push("          Object.assign(out, doc);");
  lines.push('          process.stdout.write(JSON.stringify(out, null, 2) + "\\n");');
  lines.push("        } else {");
  lines.push("          // YAML output");
  lines.push("          const yamlLines: string[] = [];");
  lines.push(`          yamlLines.push("# ${executable} extract");`);
  lines.push(`          yamlLines.push("# source: embedded");`);
  lines.push(`          yamlLines.push("# type: cli-contracts/command-extract");`);
  lines.push("          if (opts.includeMeta) {");
  lines.push('            yamlLines.push("---");');
  lines.push(`            yamlLines.push("source: embedded");`);
  lines.push(`            yamlLines.push("type: cli-contracts/command-extract");`);
  lines.push(`            yamlLines.push("extractedAt: " + new Date().toISOString());`);
  lines.push(`            yamlLines.push("spec_version: " + (doc.cli_contracts ?? "0.1.0"));`);
  lines.push(`            yamlLines.push("commands:");`);
  lines.push(`            for (const id of ${JSON.stringify(allFullIds)}) {`);
  lines.push(`              yamlLines.push("  - " + id);`);
  lines.push("            }");
  lines.push("          }");
  lines.push('          yamlLines.push("---");');
  lines.push("          yamlLines.push(CONTRACT_YAML);");
  lines.push('          process.stdout.write(yamlLines.join("\\n") + "\\n");');
  lines.push("        }");
  lines.push("      } else {");
  lines.push("        // Filter specific commands");
  lines.push("        const filtered: Record<string, unknown> = {");
  lines.push("          cli_contracts: doc.cli_contracts,");
  lines.push("          info: doc.info,");
  lines.push("          command_sets: {},");
  lines.push("        };");
  lines.push("        const fcs = filtered.command_sets as Record<string, Record<string, unknown>>;");
  lines.push("        for (const [setId, cs] of Object.entries(doc.command_sets ?? {})) {");
  lines.push("          const cmds = (cs as Record<string, unknown>).commands as Record<string, unknown> | undefined;");
  lines.push("          if (!cmds) continue;");
  lines.push("          const matched: Record<string, unknown> = {};");
  lines.push("          for (const [cmdId, cmdDef] of Object.entries(cmds)) {");
  lines.push("            const fullId = setId + \".\" + cmdId;");
  lines.push("            if (cmdIds.some((id) => id === cmdId || id === fullId || cmdId.startsWith(id + \".\"))) {");
  lines.push("              matched[cmdId] = cmdDef;");
  lines.push("            }");
  lines.push("          }");
  lines.push("          if (Object.keys(matched).length > 0) {");
  lines.push("            const setCopy = { ...(cs as Record<string, unknown>) };");
  lines.push("            setCopy.commands = matched;");
  lines.push("            fcs[setId] = setCopy;");
  lines.push("          }");
  lines.push("        }");
  lines.push("        if (doc.components) filtered.components = doc.components;");
  lines.push('        process.stdout.write(JSON.stringify(filtered, null, 2) + "\\n");');
  lines.push("      }");
  lines.push("      process.exit(0);");
  lines.push("    });");
}
